import{a as E,S as $,i as c}from"./assets/vendor-xwsNXkQR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const R="52835666-1230dcd88b93a283721c6818c",f=15;async function p(o,t){const n=`https://pixabay.com/api/?${new URLSearchParams({key:R,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f})}`;try{return(await E.get(n)).data}catch(e){throw new Error(`Failed to fetch images: ${e.message}`)}}const g=f,h=document.querySelector(".gallery"),y=document.querySelector(".loader"),b=document.querySelector(".load-more-btn"),M=new $(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});function L(o){const t=o.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:i,comments:q,downloads:v})=>`
        <li class="gallery-item">
            <a href="${n}" class="gallery-link">
                <img src="${a}" alt="${e}" class="gallery-image" width="300">
            </a>
            <div class="gallery-info">
                <p><b>Likes:</b> ${r}</p>
                <p><b>Views:</b> ${i}</p>
                <p><b>Comments:</b> ${q}</p>
                <p><b>Downloads:</b> ${v}</p>
            </div>
        </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),M.refresh()}function B(){h.innerHTML=""}function w(){y.classList.remove("hidden")}function P(){y.classList.add("hidden")}function S(){b.classList.remove("hidden")}function d(){b.classList.add("hidden")}function I(){const o=h.firstElementChild;if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}const u=document.querySelector(".form"),A=document.querySelector(".load-more-btn");let s=1,m="",l=0;u.addEventListener("submit",O);A.addEventListener("click",x);async function O(o){o.preventDefault();const t=u.elements["search-text"].value.trim();if(!t){c.error({title:"Error",message:"Please enter a search query",position:"topRight"});return}m=t,s=1,l=0,B(),d(),w();try{const a=await p(m,s);if(l=a.totalHits,a.hits.length===0){c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}L(a.hits),l>g&&S()}catch(a){console.error("Error:",a),c.error({title:"Request Failed",message:"An error occurred while fetching data. Please check connection.",position:"topRight"})}finally{P(),u.reset()}}async function x(){s+=1,w(),d();try{const t=(await p(m,s)).hits;L(t),I(),s*g>=l||t.length===0?(d(),c.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})):S()}catch(o){console.error("Error:",o),c.error({title:"Request Failed",message:"An error occurred while fetching data. Please check connection.",position:"topRight"}),s-=1}finally{P()}}
//# sourceMappingURL=index.js.map
